# Generated by Django 5.1.7 on 2025-03-30 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='opinionapp.reaction'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
